Fix getMe Information on README
When I tried to use this function I get this error:

`UnhandledPromiseRejectionWarning: TypeError: client.getMyUser is not a function`.

I search by "getMyUser" on code base I did not find it. So I think that the correct function is `getMe` instead of `getMyUSer